name: Tests on Windows

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Set up JDK 1.8
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: zulu

      - name: Configure the environment
        shell: bash
        run: chmod +x ./gradlew
             && chmod +x ./config/scripts/publish-artifacts.sh
             && chmod +x ./config/scripts/update-apt.sh
             && ./config/scripts/update-apt.sh
             && sudo apt-get install dart
             && pub global activate protoc_plugin
             && pub global activate dart_code_gen

      - name: Build project and run tests
        shell: bash
        run: ./gradlew build --stacktrace