name: Build under Ubuntu

on:
  pull_request:
    branches:
      - master
      - 1.x-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: zulu

      - name: Update APT
        shell: bash
        run: chmod +x ./config/scripts/update-apt.sh
          && ./config/scripts/update-apt.sh

      - name: Install Dart
        shell: bash
        run: sudo apt-get install dart

      - name: Activate `protoc-plugin`
        shell: bash
        run: dart pub global activate protoc_plugin

      - name: Activate `dart_code_gen`
        shell: bash
        run: dart pub global activate dart_code_gen

      - name: Run Gradle build
        shell: bash
        run: ./gradlew build



